'use client'

import Link from 'next/link'
import Header from '../../../components/Header'
import Footer from '../../../components/Footer'
import { giveaway, formatGiveawayDate } from '../../../lib/giveaway'

/**
 * Official Rules document.
 *
 * This is a TEMPLATE based on standard US sweepstakes practice for prizes
 * under $5,000. Have it reviewed by counsel or a CPA before launch, or
 * substitute Official Rules generated by ViralSweep / similar service.
 *
 * If `giveaway.externalRulesUrl` is set, this page redirects users there
 * instead of rendering the template. That's the recommended path —
 * ViralSweep's generated rules are maintained by sweepstakes lawyers.
 */
export default function GiveawayRulesPage() {
  // If external rules are configured, surface a link rather than the template
  if (giveaway.externalRulesUrl) {
    return (
      <div className="min-h-screen bg-gray-900">
        <Header />
        <section className="py-24">
          <div className="container mx-auto px-4 sm:px-6 max-w-2xl text-center">
            <h1 className="text-3xl sm:text-4xl font-bold text-white mb-6">
              Official Rules
            </h1>
            <p className="text-gray-300 mb-8">
              The official rules for this sweepstakes are hosted off-site:
            </p>
            <a
              href={giveaway.externalRulesUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-block bg-gradient-to-r from-purple-500 to-teal-600 hover:from-purple-600 hover:to-teal-700 text-white font-semibold py-3 px-8 rounded-full transition-all"
            >
              View Official Rules →
            </a>
          </div>
        </section>
        <Footer />
      </div>
    )
  }

  const startDate = formatGiveawayDate(giveaway.startDate)
  const endDate = formatGiveawayDate(giveaway.endDate)
  const excluded =
    giveaway.excludedStates.length > 0
      ? giveaway.excludedStates.join(', ')
      : 'none'

  return (
    <div className="min-h-screen bg-gray-900">
      <Header />

      <section className="py-12 sm:py-16">
        <div className="container mx-auto px-4 sm:px-6 max-w-3xl">
          <div className="mb-8">
            <Link
              href="/giveaway"
              className="text-teal-400 hover:text-teal-300 text-sm"
            >
              ← Back to giveaway
            </Link>
          </div>

          <article className="prose prose-invert max-w-none">
            <h1 className="text-3xl sm:text-4xl font-bold text-white mb-2">
              Official Rules
            </h1>
            <p className="text-purple-300 font-semibold mb-8">
              {giveaway.name}
            </p>

            <div className="bg-yellow-900/30 border border-yellow-600/40 text-yellow-100 rounded-lg p-4 mb-8 text-sm">
              <strong>NO PURCHASE OR PAYMENT OF ANY KIND IS NECESSARY TO ENTER OR
              WIN.</strong> A purchase will not increase your chances of winning.
              Void where prohibited by law.
            </div>

            <Section title="1. Sponsor">
              <p>
                The {giveaway.name} (the &ldquo;Promotion&rdquo;) is sponsored by{' '}
                <strong>{giveaway.sponsor.legalName}</strong>, located at{' '}
                {giveaway.sponsor.address} (the &ldquo;Sponsor&rdquo;).
              </p>
            </Section>

            <Section title="2. Eligibility">
              <p>
                The Promotion is open only to legal residents of the fifty (50)
                United States and the District of Columbia, excluding residents of{' '}
                {excluded}, who are at least {giveaway.minAge} years of age (or
                the age of majority in their state of residence, whichever is
                older) at the time of entry. Employees, officers, directors, and
                agents of Sponsor and their immediate family members and persons
                residing in the same household are not eligible. Void where
                prohibited or restricted by law.
              </p>
            </Section>

            <Section title="3. Promotion Period">
              <p>
                The Promotion begins on {startDate} at 12:00:01 a.m. Eastern Time
                (&ldquo;ET&rdquo;) and ends on {endDate} at 11:59:59 p.m. ET (the
                &ldquo;Promotion Period&rdquo;). Sponsor&rsquo;s computer is the
                official timekeeping device for the Promotion.
              </p>
            </Section>

            <Section title="4. How to Enter">
              <p>
                <strong>
                  NO PURCHASE NECESSARY TO ENTER OR WIN. A PURCHASE WILL NOT
                  IMPROVE YOUR CHANCES OF WINNING.
                </strong>{' '}
                Every entry — whether earned by free email submission, free
                mail-in submission, or any purchase- or action-based bonus —
                has the <strong>same statistical chance</strong> of being
                selected as the winning entry. A purchaser does not have better
                per-entry odds than a non-purchaser; a purchaser simply may
                accumulate more individual entries. A non-purchasing entrant
                can match any entry total by submitting additional free
                mail-in entries (one (1) entry per separate outer mailing
                envelope), each of which carries the same per-entry odds as any
                paid or bonus entry.
              </p>

              <p>
                During the Promotion Period, you may enter using any of the
                methods below.
              </p>

              <p className="font-semibold text-white mt-4">
                a. Free Online Entry:
              </p>
              <p>
                Visit{' '}
                <span className="text-teal-300">
                  https://specialtybuilt.com/giveaway
                </span>{' '}
                and submit the requested information through the entry form.
                This is the standard, free method of entry. Limit one (1) free
                online entry per person per day.
              </p>

              <p className="font-semibold text-white mt-4">
                b. Free Mail-In Entry (Alternative Method of Entry / AMOE):
              </p>
              <p>
                To enter without internet access or without making a purchase,
                hand print your full name, complete street address, city, state,
                ZIP code, daytime telephone number, email address, and date of
                birth on a 3&rdquo; x 5&rdquo; piece of paper and mail it in a
                #10 envelope to:{' '}
                <strong>
                  {giveaway.name} — Mail-In Entry, c/o{' '}
                  {giveaway.sponsor.legalName}, {giveaway.sponsor.address}
                </strong>
                . Limit one (1) mail-in entry per outer mailing envelope.{' '}
                <strong>
                  There is no limit on the number of separate envelopes a
                  person may send during the Promotion Period; each separate
                  envelope counts as one (1) entry and has the same per-entry
                  odds of winning as any other entry, including any
                  purchase-based bonus entry.
                </strong>{' '}
                Mail-in entries must be postmarked by {endDate} and received by
                Sponsor no later than seven (7) days after the end of the
                Promotion Period to be eligible. Mechanically reproduced
                entries are not eligible. Sponsor is not responsible for lost,
                late, misdirected, mutilated, illegible, postage-due, or
                undelivered mail-in entries.
              </p>

              <p className="font-semibold text-white mt-4">
                c. Bonus Entries (Optional):
              </p>
              <p>
                After completing a free entry, you may earn additional bonus
                entries by completing one or more optional actions during the
                Promotion Period (entry counts subject to verification by
                Sponsor). The bonus actions available for this Promotion may
                include, without limitation: following Sponsor on social
                media, subscribing to Sponsor&rsquo;s newsletter, referring a
                friend who completes a valid entry, and making a qualifying
                purchase at specialtybuilt.com.
              </p>
              <p>
                The current bonus action for purchases is:{' '}
                <strong>
                  one (1) entry per US$1.00 spent on order subtotal (excluding
                  tax and shipping)
                </strong>
                . The complete and authoritative list of bonus actions and
                their entry values is displayed on the entry form at{' '}
                <span className="text-teal-300">
                  https://specialtybuilt.com/giveaway
                </span>{' '}
                during the Promotion Period. Sponsor reserves the right to
                add, remove, or modify bonus actions at any time during the
                Promotion Period.
              </p>
              <p>
                <strong>
                  Each bonus entry — whether earned by purchase or by any free
                  action — carries the same per-entry odds of being selected
                  as the winning entry as any free email entry or free mail-in
                  entry.
                </strong>{' '}
                Purchase will not increase your chances of winning beyond the
                bonus entries described, and a non-purchasing entrant who
                submits an equal number of free entries (online and/or
                mail-in) has the same overall chance of winning as a
                purchasing entrant with the same number of entries.
              </p>
            </Section>

            <Section title="5. Prize">
              <p>{giveaway.prizeDescription}</p>
              <p>
                Prize is awarded &ldquo;as is&rdquo; with no warranty or guarantee,
                either express or implied, by Sponsor. Prize is non-transferable.
                No cash redemption or substitution of the prize is permitted,
                except by Sponsor, which reserves the right to substitute a prize
                of equal or greater value if the advertised prize becomes
                unavailable for any reason.
              </p>
            </Section>

            <Section title="6. Winner Selection and Notification">
              <p>
                On or about {endDate}, Sponsor (or its designated representative)
                will select one (1) potential winner in a random drawing from
                among all eligible entries received during the Promotion Period.
                The odds of winning depend on the total number of eligible
                entries received.
              </p>
              <p>
                The potential winner will be notified by email at the address
                provided with the entry. The potential winner must respond to
                Sponsor&rsquo;s notification within seven (7) days. If the
                potential winner cannot be reached, fails to respond within the
                stated time, declines the prize, is found to be ineligible, or
                fails to fulfill any other requirement of these Official Rules,
                an alternate winner may be selected at Sponsor&rsquo;s discretion
                from the remaining eligible entries.
              </p>
              <p>
                As a condition of receiving the prize, the potential winner may
                be required to (a) complete and return an Affidavit of
                Eligibility, Liability Release, and (where lawful) Publicity
                Release, and (b) provide a completed IRS Form W-9 or equivalent
                tax documentation.
              </p>
            </Section>

            <Section title="7. Taxes">
              <p>
                <strong>
                  All federal, state, and local taxes on the prize, including
                  income tax owed on the cash bonus, are the sole responsibility
                  of the winner.
                </strong>{' '}
                Sponsor will issue an IRS Form 1099-MISC reporting the
                Approximate Retail Value of the prize (${giveaway.prizeARV} USD)
                to the winner and to the Internal Revenue Service. The cash
                bonus included with the prize is intended as an estimate to
                assist with tax obligations and does not guarantee that the
                winner will not owe additional tax.
              </p>
            </Section>

            <Section title="8. General Conditions">
              <p>
                Sponsor reserves the right to cancel, suspend, or modify the
                Promotion or these Official Rules if any fraud, technical
                failures, human error, or any other factor impairs the integrity
                or proper functioning of the Promotion, as determined by Sponsor
                in its sole discretion. Any attempt by any person to undermine
                the legitimate operation of the Promotion may be a violation of
                criminal and civil law, and, should such an attempt be made,
                Sponsor reserves the right to seek damages and other remedies to
                the fullest extent permitted by law.
              </p>
            </Section>

            <Section title="9. Release and Limitation of Liability">
              <p>
                By entering the Promotion, each entrant agrees to release and
                hold harmless Sponsor, its parent companies, subsidiaries,
                affiliates, partners, advertising and promotion agencies,
                successors, agents, assigns, employees, officers, and directors
                from any liability, illness, injury, death, loss, litigation,
                claim, or damage that may occur, directly or indirectly, whether
                caused by negligence or not, from (i) such entrant&rsquo;s
                participation in the Promotion and/or his/her acceptance,
                possession, use, or misuse of any prize or any portion thereof,
                (ii) technical failures of any kind, including but not limited
                to the malfunctioning of any computer, cable, network, hardware,
                or software, or other mechanical equipment, (iii) the
                unavailability or inaccessibility of any transmissions, telephone,
                or Internet service, (iv) unauthorized human intervention in any
                part of the entry process or the Promotion, (v) electronic or
                human error in the administration of the Promotion or the
                processing of entries.
              </p>
            </Section>

            <Section title="10. Disputes / Governing Law">
              <p>
                Except where prohibited, each entrant agrees that any and all
                disputes, claims, and causes of action arising out of, or
                connected with, the Promotion or any prize awarded shall be
                resolved individually, without resort to any form of class
                action, and exclusively by the appropriate state or federal
                court located in the state in which Sponsor maintains its
                principal place of business. All issues and questions concerning
                the construction, validity, interpretation, and enforceability
                of these Official Rules, or the rights and obligations of the
                entrant and Sponsor in connection with the Promotion, shall be
                governed by, and construed in accordance with, the laws of that
                state, without giving effect to any choice of law or conflict of
                law rules.
              </p>
            </Section>

            <Section title="11. Privacy">
              <p>
                Information submitted with an entry is subject to
                Sponsor&rsquo;s{' '}
                <Link href="/privacy" className="text-teal-300">
                  Privacy Policy
                </Link>
                . By entering, you consent to Sponsor&rsquo;s collection and use
                of your personal information as described in the Privacy Policy
                and agree that Sponsor has the right to verify the eligibility
                of each entrant.
              </p>
            </Section>

            <Section title="12. Winner&rsquo;s List">
              <p>
                For the name of the winner (available approximately thirty (30)
                days after the end of the Promotion Period), visit{' '}
                <Link href="/giveaway/winner" className="text-teal-300">
                  specialtybuilt.com/giveaway/winner
                </Link>{' '}
                or send a self-addressed, stamped envelope to:{' '}
                <strong>
                  {giveaway.name} — Winner Request, c/o {giveaway.sponsor.legalName},{' '}
                  {giveaway.sponsor.address}
                </strong>
                . Requests must be received within ninety (90) days of the end
                of the Promotion Period.
              </p>
            </Section>

            <p className="text-sm text-gray-500 mt-12 pt-6 border-t border-gray-700">
              Last updated: {formatGiveawayDate(giveaway.startDate)}.
            </p>
          </article>
        </div>
      </section>

      <Footer />
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="text-xl sm:text-2xl font-bold text-white mb-3">{title}</h2>
      <div className="text-gray-300 space-y-3 text-sm sm:text-base leading-relaxed">
        {children}
      </div>
    </section>
  )
}
